# Generated by Django 3.0.6 on 2021-04-03 11:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productkeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productkey', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
